<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <RootNamespace>HikIsapi</RootNamespace>
    <AssemblyName>hik-isapi-win</AssemblyName>
    <AssemblyTitle>蝕本成工具站</AssemblyTitle>
    <Product>蝕本成工具站</Product>
    <Description>蝕本成工具站</Description>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <ApplicationIcon>app.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="app.ico" LogicalName="HikIsapi.app.ico" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\HikIsapi.Core\HikIsapi.Core.csproj" />
  </ItemGroup>
</Project>
